import { useMemo, useState } from "react";
import { Search, SlidersHorizontal } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useStore } from "@/lib/store";
import { ProductCard } from "./ProductCard";

export function CatalogPage({offersOnly=false}:{offersOnly?:boolean}){
 const {products,categories}=useStore(); const [q,setQ]=useState(""); const [category,setCategory]=useState(""); const [stock,setStock]=useState(""); const [sort,setSort]=useState("relevant");
 const shown=useMemo(()=>products.filter(p=>(!offersOnly||p.promotion)&&(!q||`${p.name} ${p.brand}`.toLowerCase().includes(q.toLowerCase()))&&(!category||p.categories?.slug===category)&&(!stock||(stock==="available"?p.stock_quantity>0:p.stock_quantity===0))).sort((a,b)=>sort==="name"?a.name.localeCompare(b.name):sort==="low"?(a.promotional_price??a.price??999999)-(b.promotional_price??b.price??999999):sort==="high"?(b.promotional_price??b.price??-1)-(a.promotional_price??a.price??-1):Number(b.featured)-Number(a.featured)),[products,q,category,stock,sort,offersOnly]);
 return <section className="page-section"><div className="container-site"><div className="page-heading"><p className="eyebrow">{offersOnly?"Condições especiais":"Catálogo completo"}</p><h1>{offersOnly?"OFERTAS DO DEPÓSITO":"PRODUTOS PARA SUA OBRA"}</h1><p>{offersOnly?"Produtos promocionais cadastrados pela loja.":"Encontre materiais para construir, reformar e cuidar da casa."}</p></div><div className="mb-8 grid gap-3 rounded-lg border border-border bg-card p-4 lg:grid-cols-[1.5fr_1fr_1fr_1fr]"><label className="relative"><Search className="absolute left-3 top-3 size-5 text-muted-foreground"/><input className="input pl-10" placeholder="Pesquisar produtos..." value={q} onChange={e=>setQ(e.target.value)}/></label><select className="input" value={category} onChange={e=>setCategory(e.target.value)}><option value="">Todas as categorias</option>{categories.map(c=><option key={c.id} value={c.slug}>{c.name}</option>)}</select><select className="input" value={stock} onChange={e=>setStock(e.target.value)}><option value="">Disponibilidade</option><option value="available">Disponível</option><option value="empty">Esgotado</option></select><select className="input" value={sort} onChange={e=>setSort(e.target.value)}><option value="relevant">Mais relevantes</option><option value="low">Menor preço</option><option value="high">Maior preço</option><option value="name">Nome A-Z</option></select></div><p className="mb-5 flex items-center gap-2 text-sm font-bold text-muted-foreground"><SlidersHorizontal className="size-4"/>{shown.length} produtos encontrados</p>{shown.length?<div className="product-grid">{shown.map(p=><ProductCard key={p.id} product={p}/>)}</div>:<div className="empty-state"><h2>Nenhum produto encontrado</h2><p>Tente remover alguns filtros.</p><Button onClick={()=>{setQ("");setCategory("");setStock("")}}>Limpar filtros</Button></div>}</div></section>;
}