import { Link } from "@tanstack/react-router";
import { MessageCircle, Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useStore } from "@/lib/store";
import { effectivePrice, formatPrice, stockLabel, whatsappUrl, type Product } from "@/lib/catalog";
import catalog from "@/assets/catalog-collage.jpg";

export function ProductCard({ product }: { product: Product }) {
  const { addToList, company } = useStore();
  const price = effectivePrice(product); const stock = stockLabel(product);
  return <article className="group overflow-hidden rounded-lg border border-border bg-card transition-transform hover:-translate-y-1"><Link to="/produto/$slug" params={{ slug: product.slug }} className="relative block aspect-square overflow-hidden bg-muted"><img src={product.main_image_url || catalog} alt={product.name} className="size-full object-cover transition-transform duration-300 group-hover:scale-[1.03]" loading="lazy"/>{product.demonstration && <span className="absolute left-3 top-3 bg-foreground px-2 py-1 text-[10px] font-black uppercase text-background">Demonstração</span>}{product.promotion && <span className="absolute right-3 top-3 bg-primary px-2 py-1 text-[10px] font-black uppercase text-primary-foreground">Oferta</span>}</Link><div className="p-4"><p className="text-xs font-bold uppercase text-muted-foreground">{product.brand} · {product.categories?.name}</p><Link to="/produto/$slug" params={{ slug: product.slug }} className="mt-1 block min-h-12 text-base font-extrabold uppercase text-foreground hover:text-primary">{product.name}</Link><div className="mt-3 flex items-end justify-between gap-2"><div>{product.promotional_price && product.price ? <p className="text-xs text-muted-foreground line-through">{formatPrice(product.price)}</p> : null}<p className="text-xl font-black">{formatPrice(price)} <small className="text-xs font-semibold text-muted-foreground">/{product.unit}</small></p></div><span className={`text-[10px] font-black ${stock === "ESGOTADO" ? "text-destructive" : "text-stock"}`}>{stock}</span></div><div className="mt-4 grid grid-cols-[1fr_auto] gap-2"><Button onClick={() => addToList(product)} disabled={stock === "ESGOTADO"}><Plus/> Adicionar</Button><Button asChild variant="outline" size="icon"><a href={whatsappUrl(company?.whatsapp, `Olá! Gostaria de consultar o produto ${product.name}.`)} target="_blank" rel="noreferrer" aria-label={`Consultar ${product.name} no WhatsApp`}><MessageCircle/></a></Button></div></div></article>;
}
